---
title: "dbtstmetaanalysis"
author: "Jonathan"
date: "January 15, 2018"
output: pdf_document
---

# Load Packages
```{r}
install.packages("metafor")
library("metafor")

install.packages("readxl")
library("readxl")

```

# Load in Data from Excel
```{r}

dbtst <- read_excel("larson(rmetaanalysis).xlsx")
View(rstudiometaanalysis)



```

# Calculate effect sizes 
```{r}

dbtst <- escalc(n1i = n_control, n2i = n_treatment, m1i = mean_control, m2i = mean_treatment, sd1i = sd_control, sd2i = sd_treatment, data = dbtst, measure = "SMD", append = TRUE)


rma_model <- rma(yi, vi, data = dbtst)
summary(rma_model)

# Need to report particular outcomes: anxiety, depression, etc




```

# Forest-Plot of All Outcomes
```{r}
forest(rma_model, slab = paste(dbtst$study, as.character(dbtst$year), sep = ", "))

# To visualize all effect sizes
# Need to report particular outcomes: anxiety, depression, etc


```

# Boxplot to seperate outcomes across studies 
```{r}
boxplot(yi ~ outcome, data = dbtst)

# To visualize different outcomes
# Need to report particular outcomes: anxiety, depression, etc
```

# Funnel Plot
```{r}
funnel(rma_model)

# A common way to investigate potential publication bias in a meta-analysis is the funnel plot. Asymmetrical distribution indicates potential publication bias.

```












# 